spring:
  rabbitmq:
    password: sy
    username: sy
    virtual-host: sy
  datasource:
    control:
      liquibase:
        default-schema: eftisy
    identifiers:
      liquibase:
        default-schema: eftisy
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.gate.syldavia.eu:8080/realms/eFTI_SY
  jpa:
    properties:
      hibernate:
        control_schema: "eftisy"
        identifiers_schema: "eftisy"

gate:
  owner: http://efti.gate.syldavia.eu
  country: SY
  ap:
    url: http://efti.gate.syldavia.eu:81/domibus/services/wsplugin
    username: syldavia_service_account
    password: Azerty59*1234567
